DELETE FROM change_logs;
DELETE FROM clinic_items;
DELETE FROM clinics;
INSERT INTO clinics (id, institution_no, name, district, address, lat, lng, phone, verified, notes, updated_by, updated_at) VALUES ('clinic_1_뉴센스의원', '12339695', '뉴센스의원', '마포구', '서울 마포구 신촌로 170 이대푸르지오시티 3층', 37.5563294, 126.9442987, '02-3272-8885', 1, '원장 직접 처방 · 일본어 상담 가능', '260528', NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_1_뉴센스의원', 'mounjaro_2.5mg', 'mounjaro', '2.5mg', 305000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_1_뉴센스의원', 'mounjaro_5mg', 'mounjaro', '5mg', 405000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_1_뉴센스의원', 'mounjaro_7.5mg', 'mounjaro', '7.5mg', 570000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_1_뉴센스의원', 'mounjaro_10mg', 'mounjaro', '10mg', 570000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_1_뉴센스의원', 'wegovy_0.25mg', 'wegovy', '0.25mg', 250000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_1_뉴센스의원', 'wegovy_0.5mg', 'wegovy', '0.5mg', 269000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_1_뉴센스의원', 'wegovy_1.0mg', 'wegovy', '1.0mg', 309000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_1_뉴센스의원', 'wegovy_1.7mg', 'wegovy', '1.7mg', 369000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_1_뉴센스의원', 'wegovy_2.4mg', 'wegovy', '2.4mg', 429000, 1, NULL);
INSERT INTO clinics (id, institution_no, name, district, address, lat, lng, phone, verified, notes, updated_by, updated_at) VALUES ('clinic_2_서울바램의원', '', '서울바램의원', '서대문구', '서울특별시 서대문구 신촌역로 22-5 신촌 청년푸드스토어 2층 53호', 37.558748, 126.942917, '02-365-7575', 0, '신촌기차역가까움', '', NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_2_서울바램의원', 'mounjaro_2.5mg', 'mounjaro', '2.5mg', 320000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_2_서울바램의원', 'mounjaro_5mg', 'mounjaro', '5mg', 430000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_2_서울바램의원', 'mounjaro_7.5mg', 'mounjaro', '7.5mg', 596000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_2_서울바램의원', 'mounjaro_10mg', 'mounjaro', '10mg', 686000, 1, NULL);
INSERT INTO clinics (id, institution_no, name, district, address, lat, lng, phone, verified, notes, updated_by, updated_at) VALUES ('clinic_3_위비앙병원', '', '위비앙병원', '마포구', '서울특별시 마포구 아현동 346-56', 37.55709, 126.952443, '02-6207-8811', 0, '아현역', '', NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_3_위비앙병원', 'mounjaro_2.5mg', 'mounjaro', '2.5mg', 305000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_3_위비앙병원', 'mounjaro_5mg', 'mounjaro', '5mg', 405000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_3_위비앙병원', 'mounjaro_7.5mg', 'mounjaro', '7.5mg', 605000, 1, NULL);
INSERT INTO clinics (id, institution_no, name, district, address, lat, lng, phone, verified, notes, updated_by, updated_at) VALUES ('clinic_4_연세위더스여성의원', '', '연세위더스여성의원', '마포구', '서울특별시 마포구 양화로 178, 11층 (동교동, 목화빌딩)', 37.5574908, 126.9251464, '02-323-1194', 0, '', '', NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_4_연세위더스여성의원', 'mounjaro_2.5mg', 'mounjaro', '2.5mg', 335000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_4_연세위더스여성의원', 'mounjaro_5mg', 'mounjaro', '5mg', 450000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_4_연세위더스여성의원', 'mounjaro_7.5mg', 'mounjaro', '7.5mg', 579000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_4_연세위더스여성의원', 'mounjaro_10mg', 'mounjaro', '10mg', 579000, 1, NULL);
INSERT INTO clinics (id, institution_no, name, district, address, lat, lng, phone, verified, notes, updated_by, updated_at) VALUES ('clinic_5_낙성대또본의원', '', '낙성대또본의원', '관악구', '서울특별시 관악구 남부순환로 1931, 3층, 4층 (봉천동, 케에타워)', 37.4772204, 126.9638055, '02-871-4737', 0, '', '', NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_5_낙성대또본의원', 'mounjaro_2.5mg', 'mounjaro', '2.5mg', 320000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_5_낙성대또본의원', 'mounjaro_5mg', 'mounjaro', '5mg', 430000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_5_낙성대또본의원', 'mounjaro_7.5mg', 'mounjaro', '7.5mg', 570000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_5_낙성대또본의원', 'mounjaro_10mg', 'mounjaro', '10mg', 580000, 1, NULL);
INSERT INTO clinics (id, institution_no, name, district, address, lat, lng, phone, verified, notes, updated_by, updated_at) VALUES ('clinic_6_서여의도의원', '', '서여의도의원', '영등포구', '서울특별시 영등포구 국회대로70길 18, 한양빌딩 2층 2호 (여의도동)', 37.5289314, 126.9203375, '02-6953-5382', 0, '', '', NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_6_서여의도의원', 'mounjaro_2.5mg', 'mounjaro', '2.5mg', 360000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_6_서여의도의원', 'mounjaro_5mg', 'mounjaro', '5mg', 480000, 1, NULL);
INSERT INTO clinics (id, institution_no, name, district, address, lat, lng, phone, verified, notes, updated_by, updated_at) VALUES ('clinic_7_로하스의원', '', '로하스의원', '영등포구', '서울특별시 영등포구 여의대로 108, 파크원 2층 201호 (여의도동)', 37.5267643, 126.9271926, '02-782-7579', 0, '', '', NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_7_로하스의원', 'mounjaro_2.5mg', 'mounjaro', '2.5mg', 349000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_7_로하스의원', 'mounjaro_5mg', 'mounjaro', '5mg', 449000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_7_로하스의원', 'mounjaro_7.5mg', 'mounjaro', '7.5mg', 599000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_7_로하스의원', 'mounjaro_10mg', 'mounjaro', '10mg', 599000, 1, NULL);
INSERT INTO clinics (id, institution_no, name, district, address, lat, lng, phone, verified, notes, updated_by, updated_at) VALUES ('clinic_8_닥터킴이비인후과의원', '', '닥터킴이비인후과의원', '영등포구', '서울특별시 영등포구 여의나루로 42, 407호 (여의도동, 여의도종합상가)', 37.5215394, 126.9248093, '02-780-7582', 0, '', '', NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_8_닥터킴이비인후과의원', 'mounjaro_2.5mg', 'mounjaro', '2.5mg', 320000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_8_닥터킴이비인후과의원', 'mounjaro_5mg', 'mounjaro', '5mg', 410000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_8_닥터킴이비인후과의원', 'mounjaro_7.5mg', 'mounjaro', '7.5mg', 560000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_8_닥터킴이비인후과의원', 'mounjaro_10mg', 'mounjaro', '10mg', 560000, 1, NULL);
INSERT INTO clinics (id, institution_no, name, district, address, lat, lng, phone, verified, notes, updated_by, updated_at) VALUES ('clinic_9_강서아이엠유의원', '', '강서아이엠유의원', '강서구', '서울특별시 강서구 마곡중앙로 55, 문영 퀸즈파크13 3층 304~306호 (마곡동)', 37.5585422, 126.8264079, '02-2661-1190', 0, '', '', NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_9_강서아이엠유의원', 'mounjaro_2.5mg', 'mounjaro', '2.5mg', 315000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_9_강서아이엠유의원', 'mounjaro_5mg', 'mounjaro', '5mg', 405000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_9_강서아이엠유의원', 'mounjaro_7.5mg', 'mounjaro', '7.5mg', 575000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_9_강서아이엠유의원', 'mounjaro_10mg', 'mounjaro', '10mg', 580000, 1, NULL);
INSERT INTO clinics (id, institution_no, name, district, address, lat, lng, phone, verified, notes, updated_by, updated_at) VALUES ('clinic_10_밴스의원_용산점', '', '밴스의원 용산점', '용산구', '서울특별시 용산구 새창로 217, 1501호 (한강로2가, 용산토투밸리)', 37.5301751, 126.9677165, '02-6956-0059', 0, '', '', NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_10_밴스의원_용산점', 'mounjaro_2.5mg', 'mounjaro', '2.5mg', 374000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_10_밴스의원_용산점', 'mounjaro_5mg', 'mounjaro', '5mg', 484000, 1, NULL);
INSERT INTO clinics (id, institution_no, name, district, address, lat, lng, phone, verified, notes, updated_by, updated_at) VALUES ('clinic_11_덕은365의원', '', '덕은365의원', '고양시', '경기도 고양시 덕양구 으뜸로 138, 311~314호 (덕은동)', 37.5800393, 126.8708873, '02-6953-4175', 0, '', '', NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_11_덕은365의원', 'mounjaro_2.5mg', 'mounjaro', '2.5mg', 360000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_11_덕은365의원', 'mounjaro_5mg', 'mounjaro', '5mg', 450000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_11_덕은365의원', 'mounjaro_7.5mg', 'mounjaro', '7.5mg', 600000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_11_덕은365의원', 'mounjaro_10mg', 'mounjaro', '10mg', 600000, 1, NULL);
INSERT INTO clinics (id, institution_no, name, district, address, lat, lng, phone, verified, notes, updated_by, updated_at) VALUES ('clinic_12_다시봄의원', '', '다시봄의원', '동작구', '서울특별시 동작구 흑석한강로 27, 106동 B104호 (흑석동, 흑석한강푸르지오상가)', 37.5048589, 126.9658328, '02-814-9119', 0, '', '', NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_12_다시봄의원', 'mounjaro_2.5mg', 'mounjaro', '2.5mg', 315000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_12_다시봄의원', 'mounjaro_5mg', 'mounjaro', '5mg', 410000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_12_다시봄의원', 'mounjaro_7.5mg', 'mounjaro', '7.5mg', 560000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_12_다시봄의원', 'mounjaro_10mg', 'mounjaro', '10mg', 560000, 1, NULL);
INSERT INTO clinics (id, institution_no, name, district, address, lat, lng, phone, verified, notes, updated_by, updated_at) VALUES ('clinic_13_필모어의원', '', '필모어의원', '종로구', '서울특별시 종로구 돈화문로 30, 3호선 종로3가역 지하2층 319-205-2호 (묘동)', 37.5706106, 126.9920933, '02-744-7255', 0, '', '', NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_13_필모어의원', 'mounjaro_2.5mg', 'mounjaro', '2.5mg', 300000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_13_필모어의원', 'mounjaro_5mg', 'mounjaro', '5mg', 385000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_13_필모어의원', 'mounjaro_7.5mg', 'mounjaro', '7.5mg', 540000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_13_필모어의원', 'mounjaro_10mg', 'mounjaro', '10mg', 540000, 1, NULL);
INSERT INTO clinics (id, institution_no, name, district, address, lat, lng, phone, verified, notes, updated_by, updated_at) VALUES ('clinic_15_종로광장정형외과', '', '종로광장정형외과', '종로구', '서울특별시 종로구 종로 223', 37.5712211, 127.0024872, '02-3675-7650', 0, '', '', NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_15_종로광장정형외과', 'mounjaro_2.5mg', 'mounjaro', '2.5mg', 330000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_15_종로광장정형외과', 'mounjaro_7.5mg', 'mounjaro', '7.5mg', 540000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_15_종로광장정형외과', 'mounjaro_10mg', 'mounjaro', '10mg', 540000, 1, NULL);
INSERT INTO clinics (id, institution_no, name, district, address, lat, lng, phone, verified, notes, updated_by, updated_at) VALUES ('clinic_16_목동기운찬마취통증의학과의원', '', '목동기운찬마취통증의학과의원', '양천구', '서울특별시 양천구 목동중앙로 85, 1동 지하1층 106,107호 (목동, 강산아파트)', 37.5370203, 126.8714588, '02-2651-6661', 0, '', '', NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_16_목동기운찬마취통증의학과의원', 'mounjaro_2.5mg', 'mounjaro', '2.5mg', 310000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_16_목동기운찬마취통증의학과의원', 'mounjaro_5mg', 'mounjaro', '5mg', 410000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_16_목동기운찬마취통증의학과의원', 'mounjaro_7.5mg', 'mounjaro', '7.5mg', 550000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_16_목동기운찬마취통증의학과의원', 'mounjaro_10mg', 'mounjaro', '10mg', 550000, 1, NULL);
INSERT INTO clinics (id, institution_no, name, district, address, lat, lng, phone, verified, notes, updated_by, updated_at) VALUES ('clinic_17_엄소아과의원', '', '엄소아과의원', '노원구', '서울특별시 노원구 상계동 수락산역 인근', 37.6774161, 127.054858, '', 0, '주소·전화번호 추가 확인 필요', '', NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_17_엄소아과의원', 'mounjaro_2.5mg', 'mounjaro', '2.5mg', 310000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_17_엄소아과의원', 'mounjaro_5mg', 'mounjaro', '5mg', 410000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_17_엄소아과의원', 'mounjaro_7.5mg', 'mounjaro', '7.5mg', 560000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_17_엄소아과의원', 'mounjaro_10mg', 'mounjaro', '10mg', 560000, 1, NULL);
INSERT INTO clinics (id, institution_no, name, district, address, lat, lng, phone, verified, notes, updated_by, updated_at) VALUES ('clinic_18_웰빙내과의원', '', '웰빙내과의원', '고양시', '경기도 고양시 일산서구 중앙로 1426, 6층 (주엽동, 일송노블레스)', 37.67018, 126.7619286, '031-912-8292', 0, '', '', NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_18_웰빙내과의원', 'mounjaro_2.5mg', 'mounjaro', '2.5mg', 310000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_18_웰빙내과의원', 'mounjaro_5mg', 'mounjaro', '5mg', 410000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_18_웰빙내과의원', 'mounjaro_7.5mg', 'mounjaro', '7.5mg', 560000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_18_웰빙내과의원', 'mounjaro_10mg', 'mounjaro', '10mg', 560000, 1, NULL);
INSERT INTO clinics (id, institution_no, name, district, address, lat, lng, phone, verified, notes, updated_by, updated_at) VALUES ('clinic_19_미래365가정의학과의원', '', '미래365가정의학과의원', '강서구', '서울특별시 강서구 화곡로 398, 홈플러스강서점앤본사사옥 4층 (등촌동)', 37.5583609, 126.8550758, '02-6958-8266', 0, '', '', NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_19_미래365가정의학과의원', 'mounjaro_2.5mg', 'mounjaro', '2.5mg', 350000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_19_미래365가정의학과의원', 'mounjaro_5mg', 'mounjaro', '5mg', 450000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_19_미래365가정의학과의원', 'mounjaro_7.5mg', 'mounjaro', '7.5mg', 580000, 1, NULL);
INSERT INTO clinic_items (clinic_id, item_key, drug, dose, price, in_stock, updated_at) VALUES ('clinic_19_미래365가정의학과의원', 'mounjaro_10mg', 'mounjaro', '10mg', 580000, 1, NULL);
